parameters:
#    knox_guru_user.example.class: KnoxGuru\Bundle\UserBundle\Example

services:
#    knox_guru_user.example:
#        class: %knox_guru_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
